Slightly more robust ivycp.

diff --git a/ivycp b/ivycp
--- a/ivycp
+++ b/ivycp
@@ -58,10 +58,10 @@ genBuildXml () {
 <project name="ivycp" default="build" xmlns:ivy="antlib:org.apache.ivy.ant">
   <taskdef resource="org/apache/ivy/ant/antlib.xml" uri="antlib:org.apache.ivy.ant" classpath="$ivyjar"/>
   <target name="build">
-    <ivy:resolve type="bundle,jar">
+    <ivy:resolve type="bundle,jar" log="quiet">
 $1
     </ivy:resolve>
-    <ivy:retrieve symlink="true"/>
+    <ivy:retrieve symlink="true" log="quiet"/>
   </target>
 </project>
 EOM
@@ -69,5 +69,12 @@ EOM
 
 genBuildXml "$(dependencyLines "$@")" > "$build"
 ant -q -f "$build" >/dev/null
-set -- $(readlink "$dir/lib"/*)
-( IFS=: && echo "$*" )
+code="$?"
+if (( code == 0 )); then
+  set -- $(readlink "$dir/lib"/*)
+  ( IFS=: && echo "$*" )
+else
+  echo >&2 "Dependency retrieval failed: $?"
+fi
+
+exit "$code"
